environment: 
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci" 

    rclone_config: "ENCRYPTED[361f52a2ded83c9f36adb388247959eb6752b364d56c595b9b490f9224c06bfcd0fc63dc978739e60e8b34a77b28eb64]"
    bot_api: "ENCRYPTED[21a1b3821387776b07a14b28053f9ce1914f8b50ced11a3c086618a67740ac3e8ec096da073e9e00ccfcf1b4154015f9]"
    
task:
    name: vince 
    timeout_in: 120m
    container:
      dockerfile: Dockerfile
      cpu: 8 
      memory: 32G 
    cd_background_script: 
     - ./cd 
    ss_script: 
      - ./ss 
    mo_background_script:
      - ./mo
    br_script: 
      - ./br 
    bu_background_script:
      - ./bu
    cu_script:
      - ./cu 
